### ISSUE TITLE
Nacizane bir kaç tavsiye

### ISSUE THREAD

**Issue by leventkantaroglu** [msaadev/seyahat_asistani#26]
Elinize emeğinize sağlık.

Güzel bir readme dosyası, güzel bir kod yapısı olacağının her daim habercisidir.

Magic number'lardan biraz daha sakınırsak, ve biraz daha extension oluşturup kullanırsak proje daha da tertiplenecektir.

Güzel mimari ve temiz kodlama için teşekkürler, iyi çalışmalar 😇

**Comment by msaadev** [comment]
> Elinize emeğinize sağlık.
> 
> Güzel bir readme dosyası, güzel bir kod yapısı olacağının her daim habercisidir.
> 
> Magic number'lardan biraz daha sakınırsak, ve biraz daha extension oluşturup kullanırsak proje daha da tertiplenecektir.
> 
> Güzel mimari ve temiz kodlama için teşekkürler, iyi çalışmalar 😇

hocam magic number ekledik ama bi login tarafinda kullandık temizlemeye de pek firsatimiz olmadı yarışmadan sonra biraz daha düzenleriz geleceginde farklı planlarımız var

**Comment by kemalbayikk** [comment]
Değerli yorumlarınız için biz teşekkür ederiz hocam.
